services:
  # ============= DATABASE ==================
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: billing_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    #ports:
    #  - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  # ============= LARAVEL (PHP-FPM) =========
  api-php:
    build:
      context: ./billing-backend
      dockerfile: docker/php.Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./billing-backend:/var/www/html
      - api_vendor:/var/www/html/vendor
      - api_storage:/var/www/html/storage
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_DATABASE: billing_app
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    restart: unless-stopped

  # ============= LARAVEL (NGINX) ===========
  api:
    image: nginx:1.27-alpine
    volumes:
      - ./billing-backend:/var/www/html:ro
      - ./billing-backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:8000"   # Laravel available at http://localhost:8000
    depends_on:
      - api-php
    restart: unless-stopped

  # ============= EXPO UI (DEV) =============
  ui:
    build:
      context: ./billing-ui
      dockerfile: docker/dev.Dockerfile
    ports:
      - "19006:19006" # Expo Web (http://localhost:19006)
      - "19000:19000" # Expo protocol (optional for devices)
      - "19001:19001" # Debugger
      - "19002:19002" # Expo UI
      - "8081:8081"   # Metro
    environment:
      EXPO_PUBLIC_API_URL: "http://localhost:8000" # UI talks to API by service name
      WATCHPACK_POLLING: "true"
      EXPO_NO_TELEMETRY: "1"
    volumes:
      - ./billing-ui:/app
      - /app/node_modules
    command: >
      bash -lc "npm ci --no-audit --no-fund && (npm run start:web || npx expo start --web)"
    depends_on:
      - api
    restart: unless-stopped

  # ============= EXPO UI (PROD WEB) ========
  ui-web:
    build:
      context: ./billing-ui
      dockerfile: docker/web.Dockerfile
    ports:
      - "8080:8080"   # Web build at http://localhost:8080
    environment:
      EXPO_PUBLIC_API_URL: "http://api:8000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  dbdata:
  api_vendor:
  api_storage:
